name: compile kernel

on:
  push:
  schedule:
    - cron: "0 4 1 * *"


jobs:
  compile_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - name: install dependencies
        run: |
          ./deps.sh
      - name: build kernel
        id: build
        env:
          KERNELDIR: linux
          ZFSDIR: zfs
          KCONFIG_CONFIG: Microsoft/config-wsl
        run: |
          ./source.sh
          ./build.sh
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: linux/arch/x86/boot/bzImage
          tag_name: ${{steps.build.outputs.tag}}
